//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("easyadsModel", "PK_UserId", "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EasyWeibo.userinfo), "platforminfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EasyWeibo.platforminfo), true)]

#endregion

namespace EasyWeibo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EasyadsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EasyadsEntities object using the connection string found in the 'EasyadsEntities' section of the application configuration file.
        /// </summary>
        public EasyadsEntities() : base("name=EasyadsEntities", "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EasyadsEntities object.
        /// </summary>
        public EasyadsEntities(string connectionString) : base(connectionString, "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EasyadsEntities object.
        /// </summary>
        public EasyadsEntities(EntityConnection connection) : base(connection, "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<platforminfo> platforminfo
        {
            get
            {
                if ((_platforminfo == null))
                {
                    _platforminfo = base.CreateObjectSet<platforminfo>("platforminfo");
                }
                return _platforminfo;
            }
        }
        private ObjectSet<platforminfo> _platforminfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userinfo> userinfo
        {
            get
            {
                if ((_userinfo == null))
                {
                    _userinfo = base.CreateObjectSet<userinfo>("userinfo");
                }
                return _userinfo;
            }
        }
        private ObjectSet<userinfo> _userinfo;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the platforminfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplatforminfo(platforminfo platforminfo)
        {
            base.AddObject("platforminfo", platforminfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userinfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserinfo(userinfo userinfo)
        {
            base.AddObject("userinfo", userinfo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="easyadsModel", Name="platforminfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class platforminfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new platforminfo object.
        /// </summary>
        /// <param name="sessionKey">Initial value of the SessionKey property.</param>
        /// <param name="refresh_token">Initial value of the Refresh_token property.</param>
        /// <param name="nick">Initial value of the Nick property.</param>
        /// <param name="platformUserId">Initial value of the PlatformUserId property.</param>
        /// <param name="platform">Initial value of the Platform property.</param>
        /// <param name="expireDate">Initial value of the ExpireDate property.</param>
        /// <param name="authDate">Initial value of the AuthDate property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static platforminfo Createplatforminfo(global::System.String sessionKey, global::System.String refresh_token, global::System.String nick, global::System.String platformUserId, global::System.Int64 platform, global::System.DateTime expireDate, global::System.DateTime authDate, global::System.Int64 id, global::System.Int64 userId)
        {
            platforminfo platforminfo = new platforminfo();
            platforminfo.SessionKey = sessionKey;
            platforminfo.Refresh_token = refresh_token;
            platforminfo.Nick = nick;
            platforminfo.PlatformUserId = platformUserId;
            platforminfo.Platform = platform;
            platforminfo.ExpireDate = expireDate;
            platforminfo.AuthDate = authDate;
            platforminfo.ID = id;
            platforminfo.UserId = userId;
            return platforminfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionKey
        {
            get
            {
                return _SessionKey;
            }
            set
            {
                OnSessionKeyChanging(value);
                ReportPropertyChanging("SessionKey");
                _SessionKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionKey");
                OnSessionKeyChanged();
            }
        }
        private global::System.String _SessionKey;
        partial void OnSessionKeyChanging(global::System.String value);
        partial void OnSessionKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Refresh_token
        {
            get
            {
                return _Refresh_token;
            }
            set
            {
                OnRefresh_tokenChanging(value);
                ReportPropertyChanging("Refresh_token");
                _Refresh_token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Refresh_token");
                OnRefresh_tokenChanged();
            }
        }
        private global::System.String _Refresh_token;
        partial void OnRefresh_tokenChanging(global::System.String value);
        partial void OnRefresh_tokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                OnNickChanging(value);
                ReportPropertyChanging("Nick");
                _Nick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nick");
                OnNickChanged();
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlatformUserId
        {
            get
            {
                return _PlatformUserId;
            }
            set
            {
                OnPlatformUserIdChanging(value);
                ReportPropertyChanging("PlatformUserId");
                _PlatformUserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlatformUserId");
                OnPlatformUserIdChanged();
            }
        }
        private global::System.String _PlatformUserId;
        partial void OnPlatformUserIdChanging(global::System.String value);
        partial void OnPlatformUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Platform
        {
            get
            {
                return _Platform;
            }
            set
            {
                OnPlatformChanging(value);
                ReportPropertyChanging("Platform");
                _Platform = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Platform");
                OnPlatformChanged();
            }
        }
        private global::System.Int64 _Platform;
        partial void OnPlatformChanging(global::System.Int64 value);
        partial void OnPlatformChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpireDate
        {
            get
            {
                return _ExpireDate;
            }
            set
            {
                OnExpireDateChanging(value);
                ReportPropertyChanging("ExpireDate");
                _ExpireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpireDate");
                OnExpireDateChanged();
            }
        }
        private global::System.DateTime _ExpireDate;
        partial void OnExpireDateChanging(global::System.DateTime value);
        partial void OnExpireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AuthDate
        {
            get
            {
                return _AuthDate;
            }
            set
            {
                OnAuthDateChanging(value);
                ReportPropertyChanging("AuthDate");
                _AuthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthDate");
                OnAuthDateChanged();
            }
        }
        private global::System.DateTime _AuthDate;
        partial void OnAuthDateChanging(global::System.DateTime value);
        partial void OnAuthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("easyadsModel", "PK_UserId", "userinfo")]
        public userinfo userinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("easyadsModel.PK_UserId", "userinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("easyadsModel.PK_UserId", "userinfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<userinfo> userinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("easyadsModel.PK_UserId", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<userinfo>("easyadsModel.PK_UserId", "userinfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="easyadsModel", Name="userinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userinfo object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="tB_UserId">Initial value of the TB_UserId property.</param>
        /// <param name="accessToken">Initial value of the AccessToken property.</param>
        /// <param name="refreshToken">Initial value of the RefreshToken property.</param>
        /// <param name="nick">Initial value of the Nick property.</param>
        /// <param name="authDate">Initial value of the AuthDate property.</param>
        /// <param name="lastLogin">Initial value of the LastLogin property.</param>
        public static userinfo Createuserinfo(global::System.Int64 userId, global::System.String tB_UserId, global::System.String accessToken, global::System.String refreshToken, global::System.String nick, global::System.DateTime authDate, global::System.DateTime lastLogin)
        {
            userinfo userinfo = new userinfo();
            userinfo.UserId = userId;
            userinfo.TB_UserId = tB_UserId;
            userinfo.AccessToken = accessToken;
            userinfo.RefreshToken = refreshToken;
            userinfo.Nick = nick;
            userinfo.AuthDate = authDate;
            userinfo.LastLogin = lastLogin;
            return userinfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TB_UserId
        {
            get
            {
                return _TB_UserId;
            }
            set
            {
                OnTB_UserIdChanging(value);
                ReportPropertyChanging("TB_UserId");
                _TB_UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TB_UserId");
                OnTB_UserIdChanged();
            }
        }
        private global::System.String _TB_UserId;
        partial void OnTB_UserIdChanging(global::System.String value);
        partial void OnTB_UserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccessToken
        {
            get
            {
                return _AccessToken;
            }
            set
            {
                OnAccessTokenChanging(value);
                ReportPropertyChanging("AccessToken");
                _AccessToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccessToken");
                OnAccessTokenChanged();
            }
        }
        private global::System.String _AccessToken;
        partial void OnAccessTokenChanging(global::System.String value);
        partial void OnAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefreshToken
        {
            get
            {
                return _RefreshToken;
            }
            set
            {
                OnRefreshTokenChanging(value);
                ReportPropertyChanging("RefreshToken");
                _RefreshToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefreshToken");
                OnRefreshTokenChanged();
            }
        }
        private global::System.String _RefreshToken;
        partial void OnRefreshTokenChanging(global::System.String value);
        partial void OnRefreshTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                OnNickChanging(value);
                ReportPropertyChanging("Nick");
                _Nick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nick");
                OnNickChanged();
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AuthDate
        {
            get
            {
                return _AuthDate;
            }
            set
            {
                OnAuthDateChanging(value);
                ReportPropertyChanging("AuthDate");
                _AuthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthDate");
                OnAuthDateChanged();
            }
        }
        private global::System.DateTime _AuthDate;
        partial void OnAuthDateChanging(global::System.DateTime value);
        partial void OnAuthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private global::System.DateTime _LastLogin;
        partial void OnLastLoginChanging(global::System.DateTime value);
        partial void OnLastLoginChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("easyadsModel", "PK_UserId", "platforminfo")]
        public EntityCollection<platforminfo> platforminfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<platforminfo>("easyadsModel.PK_UserId", "platforminfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<platforminfo>("easyadsModel.PK_UserId", "platforminfo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
