//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("EasyadsModel", "PK_UserId", "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EasyWeibo.Model.userinfo), "platforminfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EasyWeibo.Model.platforminfo), true)]
[assembly: EdmRelationshipAttribute("EasyadsModel", "FK_Message_UserInfo", "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EasyWeibo.Model.userinfo), "message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EasyWeibo.Model.message), true)]

#endregion

namespace EasyWeibo.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class EasyadsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“EasyadsEntities”部分中的连接字符串初始化新 EasyadsEntities 对象。
        /// </summary>
        public EasyadsEntities() : base("name=EasyadsEntities", "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 EasyadsEntities 对象。
        /// </summary>
        public EasyadsEntities(string connectionString) : base(connectionString, "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 EasyadsEntities 对象。
        /// </summary>
        public EasyadsEntities(EntityConnection connection) : base(connection, "EasyadsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<platforminfo> platforminfo
        {
            get
            {
                if ((_platforminfo == null))
                {
                    _platforminfo = base.CreateObjectSet<platforminfo>("platforminfo");
                }
                return _platforminfo;
            }
        }
        private ObjectSet<platforminfo> _platforminfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<userinfo> userinfo
        {
            get
            {
                if ((_userinfo == null))
                {
                    _userinfo = base.CreateObjectSet<userinfo>("userinfo");
                }
                return _userinfo;
            }
        }
        private ObjectSet<userinfo> _userinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<message> message
        {
            get
            {
                if ((_message == null))
                {
                    _message = base.CreateObjectSet<message>("message");
                }
                return _message;
            }
        }
        private ObjectSet<message> _message;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 platforminfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToplatforminfo(platforminfo platforminfo)
        {
            base.AddObject("platforminfo", platforminfo);
        }
    
        /// <summary>
        /// 用于向 userinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouserinfo(userinfo userinfo)
        {
            base.AddObject("userinfo", userinfo);
        }
    
        /// <summary>
        /// 用于向 message EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomessage(message message)
        {
            base.AddObject("message", message);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EasyadsModel", Name="message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class message : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 message 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="pId">PId 属性的初始值。</param>
        /// <param name="message1">Message1 属性的初始值。</param>
        public static message Createmessage(global::System.Int64 id, global::System.Int64 userId, global::System.Int64 pId, global::System.String message1)
        {
            message message = new message();
            message.ID = id;
            message.UserId = userId;
            message.PId = pId;
            message.Message1 = message1;
            return message;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PId
        {
            get
            {
                return _PId;
            }
            set
            {
                OnPIdChanging(value);
                ReportPropertyChanging("PId");
                _PId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PId");
                OnPIdChanged();
            }
        }
        private global::System.Int64 _PId;
        partial void OnPIdChanging(global::System.Int64 value);
        partial void OnPIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message1
        {
            get
            {
                return _Message1;
            }
            set
            {
                OnMessage1Changing(value);
                ReportPropertyChanging("Message1");
                _Message1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message1");
                OnMessage1Changed();
            }
        }
        private global::System.String _Message1;
        partial void OnMessage1Changing(global::System.String value);
        partial void OnMessage1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                OnPicUrlChanging(value);
                ReportPropertyChanging("PicUrl");
                _PicUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicUrl");
                OnPicUrlChanged();
            }
        }
        private global::System.String _PicUrl;
        partial void OnPicUrlChanging(global::System.String value);
        partial void OnPicUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VideoUrl
        {
            get
            {
                return _VideoUrl;
            }
            set
            {
                OnVideoUrlChanging(value);
                ReportPropertyChanging("VideoUrl");
                _VideoUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VideoUrl");
                OnVideoUrlChanged();
            }
        }
        private global::System.String _VideoUrl;
        partial void OnVideoUrlChanging(global::System.String value);
        partial void OnVideoUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EasyadsModel", "FK_Message_UserInfo", "userinfo")]
        public userinfo userinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.FK_Message_UserInfo", "userinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.FK_Message_UserInfo", "userinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<userinfo> userinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.FK_Message_UserInfo", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<userinfo>("EasyadsModel.FK_Message_UserInfo", "userinfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EasyadsModel", Name="platforminfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class platforminfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 platforminfo 对象。
        /// </summary>
        /// <param name="sessionKey">SessionKey 属性的初始值。</param>
        /// <param name="refresh_token">Refresh_token 属性的初始值。</param>
        /// <param name="nick">Nick 属性的初始值。</param>
        /// <param name="platformUserId">PlatformUserId 属性的初始值。</param>
        /// <param name="platform">Platform 属性的初始值。</param>
        /// <param name="expireDate">ExpireDate 属性的初始值。</param>
        /// <param name="authDate">AuthDate 属性的初始值。</param>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        public static platforminfo Createplatforminfo(global::System.String sessionKey, global::System.String refresh_token, global::System.String nick, global::System.String platformUserId, global::System.String platform, global::System.DateTime expireDate, global::System.DateTime authDate, global::System.Int64 id, global::System.Int64 userId)
        {
            platforminfo platforminfo = new platforminfo();
            platforminfo.SessionKey = sessionKey;
            platforminfo.Refresh_token = refresh_token;
            platforminfo.Nick = nick;
            platforminfo.PlatformUserId = platformUserId;
            platforminfo.Platform = platform;
            platforminfo.ExpireDate = expireDate;
            platforminfo.AuthDate = authDate;
            platforminfo.ID = id;
            platforminfo.UserId = userId;
            return platforminfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionKey
        {
            get
            {
                return _SessionKey;
            }
            set
            {
                OnSessionKeyChanging(value);
                ReportPropertyChanging("SessionKey");
                _SessionKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionKey");
                OnSessionKeyChanged();
            }
        }
        private global::System.String _SessionKey;
        partial void OnSessionKeyChanging(global::System.String value);
        partial void OnSessionKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Refresh_token
        {
            get
            {
                return _Refresh_token;
            }
            set
            {
                OnRefresh_tokenChanging(value);
                ReportPropertyChanging("Refresh_token");
                _Refresh_token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Refresh_token");
                OnRefresh_tokenChanged();
            }
        }
        private global::System.String _Refresh_token;
        partial void OnRefresh_tokenChanging(global::System.String value);
        partial void OnRefresh_tokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                OnNickChanging(value);
                ReportPropertyChanging("Nick");
                _Nick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nick");
                OnNickChanged();
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlatformUserId
        {
            get
            {
                return _PlatformUserId;
            }
            set
            {
                OnPlatformUserIdChanging(value);
                ReportPropertyChanging("PlatformUserId");
                _PlatformUserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlatformUserId");
                OnPlatformUserIdChanged();
            }
        }
        private global::System.String _PlatformUserId;
        partial void OnPlatformUserIdChanging(global::System.String value);
        partial void OnPlatformUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Platform
        {
            get
            {
                return _Platform;
            }
            set
            {
                OnPlatformChanging(value);
                ReportPropertyChanging("Platform");
                _Platform = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Platform");
                OnPlatformChanged();
            }
        }
        private global::System.String _Platform;
        partial void OnPlatformChanging(global::System.String value);
        partial void OnPlatformChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpireDate
        {
            get
            {
                return _ExpireDate;
            }
            set
            {
                OnExpireDateChanging(value);
                ReportPropertyChanging("ExpireDate");
                _ExpireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpireDate");
                OnExpireDateChanged();
            }
        }
        private global::System.DateTime _ExpireDate;
        partial void OnExpireDateChanging(global::System.DateTime value);
        partial void OnExpireDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AuthDate
        {
            get
            {
                return _AuthDate;
            }
            set
            {
                OnAuthDateChanging(value);
                ReportPropertyChanging("AuthDate");
                _AuthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthDate");
                OnAuthDateChanged();
            }
        }
        private global::System.DateTime _AuthDate;
        partial void OnAuthDateChanging(global::System.DateTime value);
        partial void OnAuthDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EasyadsModel", "PK_UserId", "userinfo")]
        public userinfo userinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.PK_UserId", "userinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.PK_UserId", "userinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<userinfo> userinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("EasyadsModel.PK_UserId", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<userinfo>("EasyadsModel.PK_UserId", "userinfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EasyadsModel", Name="userinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 userinfo 对象。
        /// </summary>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="tB_UserId">TB_UserId 属性的初始值。</param>
        /// <param name="accessToken">AccessToken 属性的初始值。</param>
        /// <param name="refreshToken">RefreshToken 属性的初始值。</param>
        /// <param name="nick">Nick 属性的初始值。</param>
        /// <param name="lastLogin">LastLogin 属性的初始值。</param>
        /// <param name="expireTime">ExpireTime 属性的初始值。</param>
        /// <param name="authDate">AuthDate 属性的初始值。</param>
        public static userinfo Createuserinfo(global::System.Int64 userId, global::System.String tB_UserId, global::System.String accessToken, global::System.String refreshToken, global::System.String nick, global::System.DateTime lastLogin, global::System.DateTime expireTime, global::System.DateTime authDate)
        {
            userinfo userinfo = new userinfo();
            userinfo.UserId = userId;
            userinfo.TB_UserId = tB_UserId;
            userinfo.AccessToken = accessToken;
            userinfo.RefreshToken = refreshToken;
            userinfo.Nick = nick;
            userinfo.LastLogin = lastLogin;
            userinfo.ExpireTime = expireTime;
            userinfo.AuthDate = authDate;
            return userinfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TB_UserId
        {
            get
            {
                return _TB_UserId;
            }
            set
            {
                OnTB_UserIdChanging(value);
                ReportPropertyChanging("TB_UserId");
                _TB_UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TB_UserId");
                OnTB_UserIdChanged();
            }
        }
        private global::System.String _TB_UserId;
        partial void OnTB_UserIdChanging(global::System.String value);
        partial void OnTB_UserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccessToken
        {
            get
            {
                return _AccessToken;
            }
            set
            {
                OnAccessTokenChanging(value);
                ReportPropertyChanging("AccessToken");
                _AccessToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccessToken");
                OnAccessTokenChanged();
            }
        }
        private global::System.String _AccessToken;
        partial void OnAccessTokenChanging(global::System.String value);
        partial void OnAccessTokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefreshToken
        {
            get
            {
                return _RefreshToken;
            }
            set
            {
                OnRefreshTokenChanging(value);
                ReportPropertyChanging("RefreshToken");
                _RefreshToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefreshToken");
                OnRefreshTokenChanged();
            }
        }
        private global::System.String _RefreshToken;
        partial void OnRefreshTokenChanging(global::System.String value);
        partial void OnRefreshTokenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                OnNickChanging(value);
                ReportPropertyChanging("Nick");
                _Nick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nick");
                OnNickChanged();
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private global::System.DateTime _LastLogin;
        partial void OnLastLoginChanging(global::System.DateTime value);
        partial void OnLastLoginChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpireTime
        {
            get
            {
                return _ExpireTime;
            }
            set
            {
                OnExpireTimeChanging(value);
                ReportPropertyChanging("ExpireTime");
                _ExpireTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpireTime");
                OnExpireTimeChanged();
            }
        }
        private global::System.DateTime _ExpireTime;
        partial void OnExpireTimeChanging(global::System.DateTime value);
        partial void OnExpireTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AuthDate
        {
            get
            {
                return _AuthDate;
            }
            set
            {
                OnAuthDateChanging(value);
                ReportPropertyChanging("AuthDate");
                _AuthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthDate");
                OnAuthDateChanged();
            }
        }
        private global::System.DateTime _AuthDate;
        partial void OnAuthDateChanging(global::System.DateTime value);
        partial void OnAuthDateChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EasyadsModel", "PK_UserId", "platforminfo")]
        public EntityCollection<platforminfo> platforminfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<platforminfo>("EasyadsModel.PK_UserId", "platforminfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<platforminfo>("EasyadsModel.PK_UserId", "platforminfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EasyadsModel", "FK_Message_UserInfo", "message")]
        public EntityCollection<message> message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<message>("EasyadsModel.FK_Message_UserInfo", "message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<message>("EasyadsModel.FK_Message_UserInfo", "message", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
